// Builds the single-file Edge Function (dist/notify.ts) = logic.js + supabase/functions/notify/notifier.js
// Usage: node tools/build-notify.mjs   → then paste dist/notify.ts into Supabase → Edge Functions → notify → Code → Deploy
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const logic = readFileSync(new URL('../logic.js', import.meta.url), 'utf8');
const notifier = readFileSync(new URL('../supabase/functions/notify/notifier.js', import.meta.url), 'utf8');
// imports must come first in an ES module: hoist the notifier's import lines above the inlined logic
const lines = notifier.split('\n');
const imports = lines.filter(l => l.startsWith('import '));
const rest = lines.filter(l => !l.startsWith('import ')).join('\n');
const out = `// @ts-nocheck\n// GENERATED by tools/build-notify.mjs — edit logic.js / notifier.js instead.\n${imports.join('\n')}\n\n// ===== logic.js =====\n${logic}\n// ===== notifier.js =====\n${rest}`;
mkdirSync(new URL('../dist/', import.meta.url), { recursive: true });
writeFileSync(new URL('../dist/notify.ts', import.meta.url), out);
console.log(`dist/notify.ts written (${out.length} bytes)`);
